services:
    php-fpm:
        build: docker
        container_name: 'pl-php'
        volumes:
            - ./app:/app
        working_dir: /app

    nginx:
        image: nginx
        container_name: 'pl-nginx'
        working_dir: /app
        ports:
            - '29998:80'
        volumes:
            - ./:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx:delegated

    rr:
        build: ./docker/rr
        container_name: 'pl-rr'
        volumes:
            -  ./app:/app
            -  ./docker/rr/.rr.yaml:/app/.rr.yaml
        working_dir: /app
        ports:
            - '29999:29999'
